# Prometheus configuration for n8n monitoring
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: n8n
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: n8n
  namespaceSelector:
    matchNames:
      - n8n
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: n8n-alerts
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
    - name: n8n.rules
      rules:
        - alert: N8nDown
          expr: up{job="n8n"} == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "n8n instance down"
            description: "n8n instance has been down for more than 5 minutes."
            
        - alert: N8nHighCPU
          expr: sum(rate(container_cpu_usage_seconds_total{container="n8n"}[5m])) / sum(container_spec_cpu_quota{container="n8n"} / container_spec_cpu_period{container="n8n"}) * 100 > 80
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "n8n high CPU usage"
            description: "n8n is using more than 80% of CPU for more than 10 minutes."
            
        - alert: N8nHighMemory
          expr: sum(container_memory_usage_bytes{container="n8n"}) / sum(container_spec_memory_limit_bytes{container="n8n"}) * 100 > 80
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "n8n high memory usage"
            description: "n8n is using more than 80% of memory for more than 10 minutes."
            
        - alert: N8nHighDiskUsage
          expr: kubelet_volume_stats_used_bytes{persistentvolumeclaim=~"data-n8n-.*"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~"data-n8n-.*"} * 100 > 80
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "n8n high disk usage"
            description: "n8n is using more than 80% of disk space for more than 10 minutes."
            
        - alert: N8nTooManyRestarts
          expr: sum(increase(kube_pod_container_status_restarts_total{container="n8n"}[1h])) > 5
          labels:
            severity: warning
          annotations:
            summary: "n8n container is restarting frequently"
            description: "n8n container has restarted more than 5 times in the last hour."
            
        - alert: N8nHighErrorRate
          expr: sum(rate(http_requests_total{container="n8n", code=~"5.."}[5m])) / sum(rate(http_requests_total{container="n8n"}[5m])) * 100 > 5
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "n8n high error rate"
            description: "n8n has a high HTTP error rate (>5%) for more than 5 minutes."